### ISSUE TITLE
Using mongoose.createConnection instead of mongose.connect

### ISSUE THREAD

**Issue by DrZorge** [sharvit/mongoose-data-seed#1]
Hi, I have some troubles with using your seeder. When I try to connect to mongodb, there is an error. which you can see in the applied screenshot. Maybe, it is better to use mongoose.createConnection instead of mongose.connect. Also, maybe there is more appropriate way to make the error warnings more informative? What do you think about it?
![img-2017-05-07-14-59-55](https://cloud.githubusercontent.com/assets/12998578/25779602/15da51ee-3336-11e7-8f57-2d3d5618a26c.png)

**Comment by sharvit** [comment]
Hi, sorry for the late response.

The errors should be more focus on the error itself and I will work on a version with better errors output.

`mongoose.connect` should be more stable while working with only one connection and it should work fine.
I am not sure why this problem happens but the `mongoose.connect` command running twice instead of only once.

Is it possible that you are connecting to MongoDB before running the `md-seed run`?
